apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: crud
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: elb
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
