apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: crud
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-pod
        image: niraulaparag/dtc-backend:c914a9d
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001 
