apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: crud
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: elb
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 80
