apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: crud

spec:
  # type: LoadBalancer
  # selector:
  #   app: frontend
  # ports:
  # - port: 3000
  #   targetPort: 80
  type: NodePort
  selector:  
    app: frontend   
  ports:
  - port: 80  
    targetPort: 80
    nodePort: 30300
    protocol: TCP
