name: Kubernetes Pipeline
description: CI/CD pipeline for Kubernetes applications
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env: 
  DOCKER_BUILDKIT: 1
  FRONTEND_IMAGE: niraulaparag/dtc-frontend
  BACKEND_IMAGE: niraulaparag/dtc-backend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> application/client/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get short commit SHA
        id: vars
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # - name: Build and push frontend image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./application/client
      #     push: true
      #     tags: ${{ env.FRONTEND_IMAGE }}:${{ env.SHA }}
      #     platforms: linux/amd64,linux/arm64
    
      # - name: Build and push backend image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./application/server
      #     push: true
      #     tags: ${{ env.BACKEND_IMAGE }}:${{ env.SHA }}
      #     platforms: linux/amd64,linux/arm64

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 & Set up Kubernetes
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Set up kubectl configuration on EC2 (if not already set)
            mkdir -p ~/directory_test
            kubectl rollout restart deployment server -n crud
            kubectl rollout restart deployment client -n crud
          EOF
      
      
          
